repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: check-added-large-files
    - id: check-ast
    - id: check-case-conflict
    - id: check-yaml
      args: ["--unsafe"]
    - id: check-toml
    - id: check-merge-conflict
    - id: check-symlinks
    - id: debug-statements
    - id: detect-private-key
    - id: end-of-file-fixer
      exclude: ".*fits"
    - id: trailing-whitespace
      exclude: ".*fits"

- repo: https://github.com/pre-commit/pygrep-hooks
  rev: v1.10.0
  hooks:
    - id: python-check-blanket-noqa
    - id: python-check-mock-methods
    - id: rst-directive-colons
    - id: rst-inline-touching-normal
    - id: text-unicode-replacement-char

- repo: https://github.com/asottile/pyupgrade
  rev: v3.3.1
  hooks:
    - id: pyupgrade
      args: ["--py38-plus"]
      exclude: "asdf/extern/.*"

- repo: https://github.com/PyCQA/autoflake
  rev: v2.1.0
  hooks:
  - id: autoflake

- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
    - id: isort

- repo: https://github.com/psf/black
  rev: 23.3.0
  hooks:
    - id: black

- repo: https://github.com/asottile/blacken-docs
  rev: 1.13.0
  hooks:
    - id: blacken-docs

- repo: https://github.com/PyCQA/flake8
  rev: 6.0.0
  hooks:
    - id: flake8
      exclude: "asdf/extern/.*|docs/.*"
